services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://test:test@pg:5432/test
    ports: 
      - "8000:8000"
    volumes:
      - ./fastapi-test:/app
    depends_on:
      pg:
        condition: service_healthy # Ждать, пока база будет реально готова

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  
  pg:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data  
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck: # Проверка "здоровья" базы
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 5s
      retries: 5


  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5040:80"
# Пример того, что обычно добавляют в docker-compose.yml

volumes:
  pgdata:
